### ISSUE TITLE
Add support for analyzing osd type (Bluestore/Filestore)

### ISSUE THREAD

**Issue by ghost** [rhos-infra/jordan#1]
Can be achieved by looking at the folder (The hard way):
  /var/lib/ceph/osd/ceph-# or when using custom cluster name /var/lib/ceph/osd/clustername-number

Or the easy  way:
`  ceph osd metadata $ID | grep -e id -e hostname -e osd_objectstore
`  OR
`  ceph osd count-metadata osd_objectstore
`  OR  
see:
* http://docs.ceph.com/docs/mimic/man/8/ceph/
* https://ceph.com/geen-categorie/ceph-osd-where-is-my-data/
* https://www.virtualtothecore.com/how-to-migrate-ceph-storage-volumes-from-filestore-to-bluestore/

**Comment by nathan-weinberg** [comment]
Closing (stale); we can revisit this in internal Red Hat channels
